apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
    spec:
      serviceAccountName: PROD_SA_RUN@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - name: demo-app
        image: demo-app
        env:
        - name: RELEASE
          value: GREEN